### PR TITLE
Add iso3Code

### PR DESCRIPTION
**Pull request by endigo**
Removed England, Wales, Northen Ireland because they don't have iso3Code.

### CODE REVIEW

**Comment by endigo** [comment]
This PR solve #7

**Comment by figengungor** [comment]
Can you add these countries with empty values for iso3Code and use the new filter feature to get the ones which has iso3Code?

**Comment by endigo** [comment]
@figengungor Hello, I added removed countries back with same iso3Code (GBR).

And convert List<Map<String, String>> to List<Country> for save time in initState.

**Comment by figengungor** [comment]
Thank you for your contribution @endigo=)

**Pull request merged**
